project:
  type: website
  output-dir: docs  # Important pour GitHub Pages

website:
  title: "Analyse d'Innovation des Entreprises"
  navbar:
    left:
      - text: "Accueil"
        href: index.qmd
      - text: "Statistiques Descriptives"
        href: statistiques.qmd
      - text: "Analyse des Données"
        href: analyse.qmd
